### ISSUE TITLE
Axis and Typographic?

### ISSUE THREAD

**Issue by CiaraBurkett** [mquandalle/meteor-stylus#1]
[Axis](http://roots.cx/axis/) and, perhaps, [Typographic](https://github.com/corysimmons/typographic) would make great additions to your stylus package!

**Comment by PEM--** [comment]
:+1:

**Comment by cryptoquick** [comment]
Haha, I was supposed to be the one to add this. I'll see what I can do.

**Comment by CiaraBurkett** [comment]
Yay! Thank you!

**Comment by cryptoquick** [comment]
No problem! Also, if you need this package sooner than @mquandalle can approve and publish #2 you might be able to clone the branch to a packages directory in your application... I think Meteor might be able to add it from there.

**Comment by mquandalle** [comment]
#2 is now merged :-)

**Comment by cryptoquick** [comment]
@mquandalle Don't forget to publish the latest changes. :smile_cat:

**Comment by PEM--** [comment]
Nice. Really nice. Thanks guys. :+1:
