### ISSUE TITLE
Use the new batch plugin API

### ISSUE THREAD

**Issue by mquandalle** [mquandalle/meteor-stylus#10]
The upcoming release of meteor will expose a new API to plugin packages that will help them to handle a set of files instead of just one, making things like `@import`s a lot easier — and less hacky. You can read more details on MDG plans and rationale [here](https://quip.com/YLcCAxtjuwsL).

This issue is essentially a reminder that we should use this new API when it will be released.

**Comment by mquandalle** [comment]
Also the stylus package in the next release of meteor (v1.2) will include some features that motivated me to fork the official package in the first place, such as source-map integration or relative imports. One remaining thing is to support some stylus libraries. Maybe instead of bundling all of these in our stylus fork should create separate packages for jeet, rupture, axis, and others, that stylus users would be able to import in their stylesheets.

Do you have some thoughts, @slava? cc @cryptoquick

**Comment by Slava** [comment]
I think if you find a way to distribute the stylus libraries in packages, this could be the best option:

``` stylus
// my-stylesheet.styl
@import 'nib' // included by default
@import '{stylus:jeet}/jeet'
@import '{stylus:rupture}/rupture'
```

or even

``` stylus
@import 'nib'
@import '{stylus:libs}/jeet'
@import '{stylus:libs}/rupture'
```

I think the current API allows this, just distribute files as "isImport: true"

**Comment by mquandalle** [comment]
Cool, I'll try to package jeet as a test.

We also add support for autoprefixer, which I guess could be extracted in its own separate package and could work with every CSS languages (and not only stylus) using https://github.com/postcss/autoprefixer. Do you think that would make sense to use the new minifier compile step API to implement this autoprefixer package (or might that slow down the build process too much, and it would be better to use another API?)

**Comment by Slava** [comment]
I think it would work for CSS yes. Admittedly, I wanted to build another build phase called "post processors" that would be a good place for such things, but sadly, it turned out to be much harder than I thought.

**Comment by Slava** [comment]
if you do it only on production, it will slow down the build process only for production ;)

**Comment by mquandalle** [comment]
I managed [to create a package](https://github.com/mquandalle/meteor-jeet) that include only the jeet mixins, and import them using the `@import {mquandalle:jeet}/jeet` @slava was referring to.

I need to think more about the preferred packaging organisation. Do we want to have one package that include multiple stylus libs (`{stylus:libs}/jeet`, `{stylus:libs}/rupture`), or one package per lib, or one package per lib but working with different pre-processors (for instance jeet is importable from stylus or SASS). @cryptoquick?

While writing this message, I also realized that I didn't use the `{ isImport: true }` option. Slava could you explain me how this option works?

**Comment by Slava** [comment]
If you don't set the import option, the file will be included even if it
wasn't used by app code. I.e. automatic compilation behavior.

In your case it might not matter as much because the jeet library only
exposes mixins
