### ISSUE TITLE
Different stylus packages, different results?

### ISSUE THREAD

**Issue by Orbyt** [mquandalle/meteor-stylus#11]
So I was using this package and i noticed that one of my buttons didnt render the same as when using a different stylus package.

Code:
jade:

``` jade
a.visit-button(href="{{pathFor 'visit'}}") Visit
```

stylus:

``` stylus
.visit-button
    font-weight 800
    border white 4px solid
    display block
    box-sizing border-box
    margin 15px auto
    padding 8px
    width 150px
    max-width 200px
    background none //rgba(240, 0, 255, .4)
    color white
    text-align center
    text-decoration none
    letter-spacing 1px
    transition all 0.3s ease-out
    &:hover
        background white
        color #101828
        transition all 0.5s ease-in
```

With other packages, the button renders as a ghost button (white border with transparent background, background opacity increases when hovered)

Basically this:

![](http://i.gyazo.com/bec3a4e95f54e24b6072b121c4f274fb.gif)

becomes this:

![](http://i.gyazo.com/2f26d9843e83f9ea70e93b6e26a5470b.gif)

With this package, the border isnt there. The other packages i used were `meteor add stylus` and `meteor add juliancwirko:s-grid` <- which includes stylus. 

Was just wondering if anyone had any idea why this would happen?

**Comment by mquandalle** [comment]
I created a clonable reproduction: https://github.com/mquandalle/meteor-stylus-issue-11.

The issue is with the order of arguments of the `border` property. You have to write `border 4px solid white` instead of `border white 4px solid`. The different in packages behaviour is probably related to the fact that we are using a more recent version of stylus.

**Comment by Orbyt** [comment]
Do you have any links that go into why they have to be in a certain order? Afaik in vanilla css the order shouldnt matter.
