### ISSUE TITLE
Controlling the load order of Stylus files

### ISSUE THREAD

**Issue by MaazAli** [mquandalle/meteor-stylus#3]
Considering that we are working with cascading style sheets the order in which they are compiled is quite important. One solution is that we manually import all stylus files but that's pretty tedious. Additionally, things like base styles that may get overwritten in other files need to always be at the top.

But even this solution can fall apart if users want to specify their stylus files per component, to have a directory structure like so: 

```
client/
  components/
    my-component/
      my-component.styl
      my-component.html
      my-component.js

```

What we need is an index.styl file where we can import our base styles, variables, mixins in the order we want. Then all stylus files in our project that we don't specify in the index file are automatically appended to the index file (while the ones that we had specified are not overwritten), also ignoring all the *.import.styl files. With this we can to a degree control the load order of the files. Or at least have variables available in our other stylus files without explicitly importing them. 

The idea of the index file comes from the following meteor sass package that does exactly this: https://github.com/fourseven/meteor-scss

If there is already a solution baked in for this problem, please point me in the right direction!

**Comment by MaazAli** [comment]
Any update on this @mquandalle

**Comment by KyleKing** [comment]
Same here, I'm having trouble compiling bootstrap stylus, but can compile it with grunt using the index file

**Comment by KyleKing** [comment]
I changed the stylus files that would be imported last from .styl to .import.styl and it works!

**Comment by gabrielhpugliese** [comment]
:+1: for this. I haven't figured out how to create a variables file yet. Tried to put on lib/ folder but nothing.

**Comment by mquandalle** [comment]
This is a problem that every CSS pre-processor encounter with the meteor build system. Hopefully a new upcoming meteor API will allows us to solve this issue. See #10 for more details.
