### ISSUE TITLE
Outdated Typographic

### ISSUE THREAD

**Issue by fyodoriv** [mquandalle/meteor-stylus#4]
Great package so far, but the Typographic is currently really outdated.
I follow official Typographic instructions and I write 

```
@import 'typographic'
typographic()
```

And it does not apply the styles. Probably the package has changed greatly since it was included first here. Please update it!

Edit: I have fixed that for myself by adding a meteor bower package and installing typograhpic from it and then importing it with 
`@import '.meteor/local/bower/typographic/stylus/typographic'`
which works, but still a minor issue exists.

**Comment by cryptoquick** [comment]
Wow! That is outdated! I wonder how it got outdated so quickly... I recall adding that package only about a month ago. I guess it's time for another round of updates.

**Comment by PEM--** [comment]
:+1:

**Comment by PEM--** [comment]
Thanks.
