### ISSUE TITLE
PC compatibility

### ISSUE THREAD

**Issue by KyleKing** [mquandalle/meteor-stylus#6]
This package works on two different Macs, but my collaborator, @kkanddd2000, is having trouble from his PC for this particular case. The rest of the stylus files compile normally. Is anyone else having an error like this?

See screenshot:
![11119078_826545477420708_1112031636_n](https://cloud.githubusercontent.com/assets/3784339/7080049/2f942412-defa-11e4-9162-67955ccf0c6a.jpg)

**Comment by mquandalle** [comment]
Did you try to remove the `\` at the end of lines?

**Comment by KyleKing** [comment]
I think we fixed this in the short term by doing just that editing the text to be one line. However, it seems to work normally with the most current Meteor for Windows!
